############# English navigation ##############
# --- Products Menu ---

# AI Infrastructure
[[main]]
name = "AI"
parent = "Products"
weight = 10

[[main]]
name = "Distributed Inference"
parent = "AI"
url = "/products/distributed-inference"

[[main]]
name = "Fabric for AI"
parent = "AI"
url = "/products/ai-fabric"

[[main]]
name = "AI Gateway"
parent = "AI"
url = "/products/ai-gateway"

# Compute
[[main]]
name = "Compute"
parent = "Products"
weight = 20

[[main]]
name = "Bare Metal"
parent = "Compute"
url = "/products/bare-metal"

[[main]]
name = "Virtual Machine"
parent = "Compute"
url = "/products/virtual-machine"

# Networking
[[main]]
name = "Networking"
parent = "Products"
weight = 30

[[main]]
name = "Private Connect (IEPL)"
parent = "Networking"
url = "/products/private-connect"

[[main]]
name = "Cloud Connect"
parent = "Networking"
url = "/products/cloud-connect"

[[main]]
name = "IP Transit & DIA"
parent = "Networking"
url = "/products/ip-transit"

[[main]]
name = "Virtual Edge"
parent = "Networking"
url = "/products/virtual-edge"

# IDC
[[main]]
name = "Colocation"
parent = "Products"
url = "/products/colocation"
weight = 40
